Feature/new frontend
R0Wi/LeapMotion-signlanguage pull request #6
Opened 2020-03-22 16:14 UTC by kinderschnitte

2020-03-22 16:49 UTC, R0Wi commented on web/templates/index.html
> +          <h2>Buchstabe</h2>
Englisch/ Deutsch?

2020-03-22 16:53 UTC, R0Wi requested changes
Please little code changes...

2020-03-22 16:53 UTC, R0Wi commented on web/webroot/js/coach.js
> +function setProbabilityToUi(probability, probabilityTable)
Unused variable `probabilityTable`

2020-03-22 19:26 UTC, kinderschnitte commented on web/templates/index.html
> +          <h2>Buchstabe</h2>
Englisch

2020-03-22 19:27 UTC, kinderschnitte commented on web/webroot/js/coach.js
> +function setProbabilityToUi(probability, probabilityTable)
Removed

2020-03-23 19:02 UTC, R0Wi approved these changes

2020-03-23 19:02 UTC, merged